### ISSUE TITLE
Wrong start index for ReadState::ServingPayload in NoiseStream

### ISSUE THREAD

**Issue by wlh320** [black-binary/snowstorm#8]
In my opinion, code in line 302 of stream.rs may be wrong:
https://github.com/black-binary/snowstorm/blob/5b2a3c0f261cb2792d76dae8da4058d1fc538587/src/stream.rs#L302

For your reference, code around this line is
https://github.com/black-binary/snowstorm/blob/5b2a3c0f261cb2792d76dae8da4058d1fc538587/src/stream.rs#L298-L308

Maybe we should read from index `start`?
For example:
```rust
 read_buf.put_slice(&read_payload_buffer[*start..*start + buf_remaining]);
```

**Comment by yujqiao** [comment]
Interesting. Can you show a case to break snowstorm?



---Original---
From: ***@***.***&gt;
Date: Thu, May 19, 2022 22:36 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [black-binary/snowstorm] Wrong start index forReadState::ServingPayload in NoiseStream (Issue #8)




 
In my opinion, code in line 302 of stream.rs may be wrong:
 https://github.com/black-binary/snowstorm/blob/5b2a3c0f261cb2792d76dae8da4058d1fc538587/src/stream.rs#L302
 
For your reference, code around this line is
 https://github.com/black-binary/snowstorm/blob/5b2a3c0f261cb2792d76dae8da4058d1fc538587/src/stream.rs#L298-L308
 
Maybe we should read from index start?
 For example:
  read_buf.put_slice(&amp;read_payload_buffer[*start..*start + buf_remaining]);

**Comment by black-binary** [comment]
```rust
if buf_remaining <= read_buf_remaining 
```

The branch means that all decrypted data (the whole slice) can be copied into the provided buffer immediately.

```rust
         read_buf.put_slice(read_payload_buffer); 
         *state = ReadState::Idle; 
```

Since the decrypted data is consumed, the reader's state can be transferred into `Idle`.

In this case, there is no need to specify the range of the slice `read_payload_buffer`. :)

**Comment by wlh320** [comment]
Thanks for your reply! `snowstorm` is a good wrapper for snow and is very easy to use.

I found this when I try to implement a `ssh -D` like function by wrapping NoiseStream with SOCKS5 using this library -> [fast-socks5](https://github.com/dizda/fast-socks5).

The code is sort of like this:
```rust
// It is a server that accepts TCPstream from client as variable `inbound`

// snowstorm part
let responder = snowstorm::Builder::new(PATTERN.parse()?)
    .local_private_key(&self.config.prikey)
    .build_responder()?;
let enc_inbound = NoiseStream::handshake_with_verifier(inbound, responder, |key| {
    let token = base64::encode(key);
    self.config.clients.contains_key(&token)
})
.await?;
// fast-socks5 part
let socks5_config = fast_socks5::server::Config::default();
let config = Arc::new(socks5_config);
let socket = Socks5Socket::new(enc_inbound, config);
let transfer = socket.upgrade_to_socks5().map(|r| {
    if let Err(e) = r {
        log::error!("Transfer error occured. error={}", e);
    }
});
transfer.await;
```
When performing SOCKS5 handshake, `fast-socks5` calls `read_exact!` twice each with 2 bytes.
First two bytes is version and methods len, in my case, [5, 2], and next two bytes is [0, 1].

When reading data the second time in `NoiseStream`, the program panics in line 302 with `buf.len() must fit in remaining()`.
I debug the program and find that at this time, len of read_payload_buffer is 4 with content [5, 2, 0, 1], and len of read_buf is 2.

I am new to rust and tokio, and I don't fully understand the logic of this library now so I just change the code to what I list in the beginning and it works, maybe I was wrong.
Thanks!

**Comment by black-binary** [comment]
Thanks for your feedback! Need some time to find out the root cause.

**Comment by black-binary** [comment]
Oh I get it. That was a stupid error. XD
Fixing

**Comment by yujqiao** [comment]
I believe this is a bug in snowstorm.


When readbuf is smaller than the data the first time and is then read so more space is available, the second call to poll read will trigger the panic.


A unit test for this case can present the bug clearly and would be helpful for black-binary to fix this. Would you like to add it? @zilch40



---Original---
From: ***@***.***&gt;
Date: Fri, May 20, 2022 00:10 AM
To: ***@***.***&gt;;
Cc: "Yujia ***@***.******@***.***&gt;;
Subject: Re: [black-binary/snowstorm] Wrong start index forReadState::ServingPayload in NoiseStream (Issue #8)




 
Thanks for your reply! snowstorm is a good wrapper for snow and is very easy to use.
 
I found this when I try to implement a ssh -D like function by wrapping NoiseStream with SOCKS5 using this library -&gt; fast-socks5.
 
The code is sort of like this:
 // It is a server that accepts TCPstream from client as variable `inbound` // snowstorm part let responder = snowstorm::Builder::new(PATTERN.parse()?)     .local_private_key(&amp;self.config.prikey)     .build_responder()?; let enc_inbound = NoiseStream::handshake_with_verifier(inbound, responder, |key| {     let token = base64::encode(key);     self.config.clients.contains_key(&amp;token) }) .await?; // fast-socks5 part let socks5_config = fast_socks5::server::Config::default(); let config = Arc::new(socks5_config); let socket = Socks5Socket::new(enc_inbound, config); let transfer = socket.upgrade_to_socks5().map(|r| {     if let Err(e) = r {         log::error!("Transfer error occured. error={}", e);     } }); transfer.await;
 
When performing SOCKS5 handshake, fast-socks5 calls read_exact! twice each with 2 bytes.
 First two bytes is version and methods len, in my case, [5, 2], and next two bytes is [0, 1].
 
When reading data the second time in NoiseStream, the program panics in line 302 with buf.len() must fit in remaining().
 I debug the program and find that at this time, len of read_payload_buffer is 4 with content [5, 2, 0, 1], and len of read_buf is 2.
 
I am new to rust and tokio, and I don't fully understand the logic of this library now so I just change the code to what I list in the beginning and it works, maybe I was wrong.
 Thanks!

**Comment by wlh320** [comment]
Yes, I just got the reason too.
One possible unit test to reproduce the bug is like this. Just a small modification of existing test, the responder reads twice from stream.
And this test can be passed after the fix.
```rust
    #[tokio::test]
    async fn tcp_read_twice() -> anyhow::Result<()> {
        static PATTERN: &str = "Noise_KK_25519_ChaChaPoly_BLAKE2s";
        let client_key = Builder::new(PATTERN.parse().unwrap())
            .generate_keypair()
            .unwrap();
        let server_key = Builder::new(PATTERN.parse().unwrap())
            .generate_keypair()
            .unwrap();

        let listener = TcpListener::bind("127.0.0.1:23333").await.unwrap();
        tokio::spawn(async move {
            let initiator = Builder::new(PATTERN.parse().unwrap())
                .local_private_key(&client_key.private)
                .remote_public_key(&server_key.public)
                .build_initiator()
                .unwrap();
            let stream = TcpStream::connect("127.0.0.1:23333").await.unwrap();
            let mut stream = NoiseStream::handshake(stream, initiator).await.unwrap();
            let payload = (0..0x20000).map(|a| a as u8).collect::<Vec<_>>();
            stream.write_all(&payload).await.unwrap();
        });

        let responder = Builder::new(PATTERN.parse().unwrap())
            .local_private_key(&server_key.private)
            .remote_public_key(&client_key.public)
            .build_responder()
            .unwrap();
        let (stream, _) = listener.accept().await.unwrap();
        let mut stream = NoiseStream::handshake(stream, responder).await.unwrap();
        println!("{:?}", stream);
        let mut payload1 = vec![0; 0x10000];
        stream.read_exact(&mut payload1).await.unwrap();
        let mut payload2 = vec![0; 0x10000];
        stream.read_exact(&mut payload2).await.unwrap();

        payload1
            .iter()
            .chain(payload2.iter())
            .enumerate()
            .for_each(|(i, v)| {
                assert_eq!(i as u8, *v);
            });

        Ok(())
    }
```
Now that the bug is fixed, I'll close this issue.
Thanks!
